package com.example.MyBookShopApp.data;

import com.fasterxml.jackson.annotation.JsonIgnore;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

@Entity
@Table(name = "author")
@ApiModel(description = "data model of author entity")
public class AuthorEntity {

  //@JsonIgnore - аннотация, чтобы не учитывать в документации поле

  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  @ApiModelProperty(value = "author id generated by db", position = 1)
  private int id;

  @OneToMany(mappedBy = "author")
//  @JoinColumn(name = "author_id", referencedColumnName = "id")
  @JsonIgnore
  private List<BookEntity> bookList = new ArrayList<>();

  @Column(columnDefinition = "VARCHAR(255)")
  private String photo;

  @Column(columnDefinition = "VARCHAR(255) NOT NULL")
  private String slug;

  @Column(columnDefinition = "VARCHAR(255) NOT NULL")
  @ApiModelProperty(value = "author name", example = "Bob Blaskovits", position = 2)
  private String name;

  @Column(columnDefinition = "TEXT")
  private String description;

  public AuthorEntity(List<String> authors) {
    if (authors != null){
      this.name = authors.toString();
    }
  }

  public AuthorEntity(){}

  @Override
  public String toString() {
    return name;
  }

  public List<BookEntity> getBookList() {
    return bookList;
  }

  public void setBookList(List<BookEntity> bookList) {
    this.bookList = bookList;
  }

  public int getId() {
    return id;
  }

  public void setId(int id) {
    this.id = id;
  }

  public String getPhoto() {
    return photo;
  }

  public void setPhoto(String photo) {
    this.photo = photo;
  }

  public String getSlug() {
    return slug;
  }

  public void setSlug(String slug) {
    this.slug = slug;
  }

  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }
}
