package com.example.MyBookShopApp.data;

import com.fasterxml.jackson.annotation.JsonIgnore;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

@Entity
@Table(name = "tag")
@ApiModel(description = "data model of tag entity")
public class TagEntity {

  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  @ApiModelProperty(value = "tag id generated by db", position = 1)
  private int id;

  @OneToMany(mappedBy = "tag")
  @JsonIgnore
  private List<BookEntity> bookList = new ArrayList<>();

  @Column(columnDefinition = "VARCHAR(255)")
  private String name;

  @Override
  public String toString() {
    return name;
  }

  public int getId() {
    return id;
  }

  public void setId(int id) {
    this.id = id;
  }

  public List<BookEntity> getBookList() {
    return bookList;
  }

  public void setBookList(List<BookEntity> bookList) {
    this.bookList = bookList;
  }

  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }
}
